package Main_dan_GUI;

import Class.*;
import javax.swing.JOptionPane;

public class Cari extends javax.swing.JDialog {

    Queue[] qlist;

    public Cari(java.awt.Frame parent, boolean modal, Queue[] queue, Queue queue1, Queue queue2, Queue queue3) {
        super(parent, modal);
        initComponents();
        panelTambah.setVisible(false);
        panelS1.setVisible(false);
        panelS2.setVisible(false);
        panelS3.setVisible(false);
        qlist = queue;
        qlist[0] = queue1;
        qlist[1] = queue2;
        qlist[2] = queue3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hairA1 = new javax.swing.JCheckBox();
        hairA2 = new javax.swing.JCheckBox();
        hairA3 = new javax.swing.JCheckBox();
        btnCari = new javax.swing.JButton();
        panelTambah = new javax.swing.JPanel();
        panelS1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        names1 = new javax.swing.JTextField();
        panelS2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        names2 = new javax.swing.JTextField();
        panelS3 = new javax.swing.JPanel();
        names3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cari ");

        hairA1.setText("Chandra");
        hairA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairA1ActionPerformed(evt);
            }
        });

        hairA2.setText("Agus");
        hairA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairA2ActionPerformed(evt);
            }
        });

        hairA3.setText("Gopinda");
        hairA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairA3ActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        panelTambah.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelS1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chandra"));
        panelS1.setPreferredSize(new java.awt.Dimension(170, 150));

        jLabel2.setText("Nama");

        names1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                names1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelS1Layout = new javax.swing.GroupLayout(panelS1);
        panelS1.setLayout(panelS1Layout);
        panelS1Layout.setHorizontalGroup(
            panelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelS1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(names1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panelS1Layout.setVerticalGroup(
            panelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelS1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(names1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelS2.setBorder(javax.swing.BorderFactory.createTitledBorder("Agus"));
        panelS2.setPreferredSize(new java.awt.Dimension(170, 150));

        jLabel4.setText("Nama");

        names2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                names2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelS2Layout = new javax.swing.GroupLayout(panelS2);
        panelS2.setLayout(panelS2Layout);
        panelS2Layout.setHorizontalGroup(
            panelS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelS2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(names2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panelS2Layout.setVerticalGroup(
            panelS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelS2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(names2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelS3.setBorder(javax.swing.BorderFactory.createTitledBorder("Gopinda"));
        panelS3.setPreferredSize(new java.awt.Dimension(170, 150));

        names3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                names3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nama");

        javax.swing.GroupLayout panelS3Layout = new javax.swing.GroupLayout(panelS3);
        panelS3.setLayout(panelS3Layout);
        panelS3Layout.setHorizontalGroup(
            panelS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelS3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(names3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        panelS3Layout.setVerticalGroup(
            panelS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelS3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(names3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTambahLayout = new javax.swing.GroupLayout(panelTambah);
        panelTambah.setLayout(panelTambahLayout);
        panelTambahLayout.setHorizontalGroup(
            panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelS1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelS2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelS3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTambahLayout.setVerticalGroup(
            panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahLayout.createSequentialGroup()
                .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelS1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(panelS2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(panelS3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelS1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hairA1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)
                        .addComponent(hairA2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)
                        .addComponent(hairA3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelTambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hairA3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hairA1)
                        .addComponent(hairA2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCari)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hairA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairA1ActionPerformed
        if (hairA1.isSelected()) {
            panelTambah.setVisible(true);
            panelS1.setVisible(true);
        } else {
            panelS1.setVisible(false);
        }
    }//GEN-LAST:event_hairA1ActionPerformed

    private void hairA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairA2ActionPerformed
        if (hairA2.isSelected()) {
            panelTambah.setVisible(true);
            panelS2.setVisible(true);
        } else {
            panelS2.setVisible(false);
        }
    }//GEN-LAST:event_hairA2ActionPerformed

    private void hairA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairA3ActionPerformed
        if (hairA3.isSelected()) {
            panelTambah.setVisible(true);
            panelS3.setVisible(true);
        } else {
            panelS3.setVisible(false);
        }
    }//GEN-LAST:event_hairA3ActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String nama;

        if (hairA1.isSelected()) {
            nama = names1.getText();
            if (qlist[0].isEmpty()) {
                JOptionPane.showMessageDialog(null, "tolong masukan data terlebih dahulu ");
            } else if (!qlist[0].isEmpty()) {
                if (qlist[0].search(nama) == null) {
                    JOptionPane.showMessageDialog(null, "Pelanggan atas nama " + nama + " tidak ada");
                } else {
                    JOptionPane.showMessageDialog(null, "Pelanggan atas nama " + nama + " reservasi pada jam : " + qlist[0].search(nama));
                }
            }
        }

        if (hairA2.isSelected()) {
            nama = names2.getText();
            if (qlist[1].isEmpty()) {
                JOptionPane.showMessageDialog(null, "tolong masukan data terlebih dahulu ");
            } else if (!qlist[1].isEmpty()) {
                if (qlist[1].search(nama) == null) {
                    JOptionPane.showMessageDialog(null, "Pelanggan atas nama " + nama + " tidak ada");
                } else {
                    JOptionPane.showMessageDialog(null, "Pelanggan atas nama " + nama + " reservasi pada jam : " + qlist[1].search(nama));
                }
            }
        }

        if (hairA3.isSelected()) {
            nama = names3.getText();
            if (qlist[2].isEmpty()) {
                JOptionPane.showMessageDialog(null, "tolong masukan data terlebih dahulu ");
            } else if (!qlist[2].isEmpty()) {
                if (qlist[2].search(nama) == null) {
                    JOptionPane.showMessageDialog(null, "Pelanggan atas nama " + nama + " tidak ada");
                } else {
                    JOptionPane.showMessageDialog(null, "Pelanggan atas nama " + nama + " reservasi pada jam : " + qlist[2].search(nama));
                }
            }
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void names1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_names1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_names1ActionPerformed

    private void names2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_names2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_names2ActionPerformed

    private void names3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_names3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_names3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JCheckBox hairA1;
    private javax.swing.JCheckBox hairA2;
    private javax.swing.JCheckBox hairA3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField names1;
    private javax.swing.JTextField names2;
    private javax.swing.JTextField names3;
    private javax.swing.JPanel panelS1;
    private javax.swing.JPanel panelS2;
    private javax.swing.JPanel panelS3;
    private javax.swing.JPanel panelTambah;
    // End of variables declaration//GEN-END:variables
}
