package Main_dan_GUI;

import Class.*;
import javax.swing.JOptionPane;

public class Tambah extends javax.swing.JDialog {

    Queue[] qlist;

    public Tambah(java.awt.Frame parent, boolean modal, Queue[] queue, Queue queue1, Queue queue2, Queue queue3) {
        super(parent, modal);
        initComponents();
        panelTambah.setVisible(false);
        panelS1.setVisible(false);
        panelS2.setVisible(false);
        panelS3.setVisible(false);
        qlist = queue;
        qlist[0] = queue1;
        qlist[1] = queue2;
        qlist[2] = queue3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hairA1 = new javax.swing.JCheckBox();
        hairA2 = new javax.swing.JCheckBox();
        hairA3 = new javax.swing.JCheckBox();
        btnTambah = new javax.swing.JButton();
        panelTambah = new javax.swing.JPanel();
        panelS1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        names1 = new javax.swing.JTextField();
        jamS1 = new javax.swing.JComboBox<>();
        panelS2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        names2 = new javax.swing.JTextField();
        jamS2 = new javax.swing.JComboBox<>();
        panelS3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        names3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jamS3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Reservasi");

        hairA1.setText("Chandra");
        hairA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairA1ActionPerformed(evt);
            }
        });

        hairA2.setText("Agus");
        hairA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairA2ActionPerformed(evt);
            }
        });

        hairA3.setText("Gopinda");
        hairA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairA3ActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        panelTambah.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelS1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chandra"));
        panelS1.setPreferredSize(new java.awt.Dimension(170, 150));

        jLabel1.setText("Jam");

        jLabel2.setText("Nama");

        names1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                names1ActionPerformed(evt);
            }
        });

        jamS1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "13.00", "14.00", "15.00", "16.00", "17.00", "19.00" }));

        javax.swing.GroupLayout panelS1Layout = new javax.swing.GroupLayout(panelS1);
        panelS1.setLayout(panelS1Layout);
        panelS1Layout.setHorizontalGroup(
            panelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelS1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelS1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(names1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelS1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jamS1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panelS1Layout.setVerticalGroup(
            panelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelS1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jamS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(names1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        panelS2.setBorder(javax.swing.BorderFactory.createTitledBorder("Agus"));
        panelS2.setPreferredSize(new java.awt.Dimension(170, 150));

        jLabel3.setText("Jam ");

        jLabel4.setText("Nama");

        names2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                names2ActionPerformed(evt);
            }
        });

        jamS2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "13.00", "14.00", "15.00", "16.00", "17.00", "19.00" }));

        javax.swing.GroupLayout panelS2Layout = new javax.swing.GroupLayout(panelS2);
        panelS2.setLayout(panelS2Layout);
        panelS2Layout.setHorizontalGroup(
            panelS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelS2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelS2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(names2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelS2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jamS2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panelS2Layout.setVerticalGroup(
            panelS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelS2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jamS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(names2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        panelS3.setBorder(javax.swing.BorderFactory.createTitledBorder("Gopinda"));
        panelS3.setPreferredSize(new java.awt.Dimension(170, 150));

        jLabel5.setText("Jam ");

        names3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                names3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nama");

        jamS3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "13.00", "14.00", "15.00", "16.00", "17.00", "19.00" }));

        javax.swing.GroupLayout panelS3Layout = new javax.swing.GroupLayout(panelS3);
        panelS3.setLayout(panelS3Layout);
        panelS3Layout.setHorizontalGroup(
            panelS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelS3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelS3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(names3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelS3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jamS3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        panelS3Layout.setVerticalGroup(
            panelS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelS3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jamS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(names3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTambahLayout = new javax.swing.GroupLayout(panelTambah);
        panelTambah.setLayout(panelTambahLayout);
        panelTambahLayout.setHorizontalGroup(
            panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelS1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelS2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelS3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTambahLayout.setVerticalGroup(
            panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahLayout.createSequentialGroup()
                .addComponent(panelS2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(panelTambahLayout.createSequentialGroup()
                .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelS1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(panelS3, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelS1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hairA1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)
                        .addComponent(hairA2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)
                        .addComponent(hairA3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelTambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hairA3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hairA1)
                        .addComponent(hairA2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hairA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairA1ActionPerformed
        if (hairA1.isSelected()) {
            panelTambah.setVisible(true);
            panelS1.setVisible(true);
        } else {
            panelS1.setVisible(false);
        }
    }//GEN-LAST:event_hairA1ActionPerformed

    private void hairA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairA2ActionPerformed
        if (hairA2.isSelected()) {
            panelTambah.setVisible(true);
            panelS2.setVisible(true);
        } else {
            panelS2.setVisible(false);
        }
    }//GEN-LAST:event_hairA2ActionPerformed

    private void hairA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairA3ActionPerformed
        if (hairA3.isSelected()) {
            panelTambah.setVisible(true);
            panelS3.setVisible(true);
        } else {
            panelS3.setVisible(false);
        }
    }//GEN-LAST:event_hairA3ActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String nama;
        String jam;

        if (hairA1.isSelected()) {
            jam = (String)jamS1.getSelectedItem();
            nama = names1.getText();

            if (qlist[0].isEmpty()) {
                addDataS1(jam, nama);
            } else {
                if(qlist[0].searchJam(jam)==null && qlist[0].search(nama)==null){
                    addDataS1(jam, nama);
                }else if(qlist[0].searchJam(jam)!=null){
                    JOptionPane.showMessageDialog(null, "Jam Tidak Boleh Sama pada Hair Artist Yang sama","Jam Sudah Dipesan", JOptionPane.WARNING_MESSAGE);
                }else if (qlist[0].search(nama)!=null) {
                    JOptionPane.showMessageDialog(null, "Nama sudah terdaftar coba ubah nama","Nama Sudah Ada", JOptionPane.WARNING_MESSAGE);
                }
            }
        }

        if (hairA2.isSelected()) {
            jam = (String)jamS2.getSelectedItem();
            nama = names2.getText();

             if (qlist[1].isEmpty()) {
                addDataS2(jam, nama);
            } else {
                if(qlist[1].searchJam(jam)==null && qlist[1].search(nama)==null){
                    addDataS2(jam, nama);
                }else if(qlist[1].searchJam(jam)!=null){
                    JOptionPane.showMessageDialog(null, "Jam Tidak Boleh Sama pada Hair Artist Yang sama","Jam Sudah Dipesan", JOptionPane.WARNING_MESSAGE);
                }else if (qlist[1].search(nama)!=null) {
                    JOptionPane.showMessageDialog(null, "Nama sudah terdaftar coba ubah nama","Nama Sudah Ada", JOptionPane.WARNING_MESSAGE);
                }
            }
        }

        if (hairA3.isSelected()) {

            jam = (String)jamS3.getSelectedItem();
            nama = names3.getText();

             if (qlist[2].isEmpty()) {
                addDataS3(jam, nama);
            } else {
                if(qlist[2].searchJam(jam)==null && qlist[2].search(nama)==null){
                    addDataS3(jam, nama);
                }else if(qlist[2].searchJam(jam)!=null){
                    JOptionPane.showMessageDialog(null, "Jam Tidak Boleh Sama pada Hair Artist Yang sama","Jam Sudah Dipesan", JOptionPane.WARNING_MESSAGE);
                }else if (qlist[2].search(nama)!=null) {
                    JOptionPane.showMessageDialog(null, "Nama sudah terdaftar coba ubah nama","Nama Sudah Ada", JOptionPane.WARNING_MESSAGE);
                }
            }

        }

        dispose();

    }//GEN-LAST:event_btnTambahActionPerformed

    private void names1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_names1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_names1ActionPerformed

    private void names2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_names2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_names2ActionPerformed

    private void names3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_names3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_names3ActionPerformed

    void addDataS1(String jam, String nama) {
        qlist[0].enqueue(new HairArtist(jam, nama));
    }

    void addDataS2(String jam, String nama) {
        qlist[1].enqueue(new HairArtist(jam, nama));
    }

    void addDataS3(String jam, String nama) {
        qlist[2].enqueue(new HairArtist(jam, nama));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambah;
    private javax.swing.JCheckBox hairA1;
    private javax.swing.JCheckBox hairA2;
    private javax.swing.JCheckBox hairA3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jamS1;
    private javax.swing.JComboBox<String> jamS2;
    private javax.swing.JComboBox<String> jamS3;
    private javax.swing.JTextField names1;
    private javax.swing.JTextField names2;
    private javax.swing.JTextField names3;
    private javax.swing.JPanel panelS1;
    private javax.swing.JPanel panelS2;
    private javax.swing.JPanel panelS3;
    private javax.swing.JPanel panelTambah;
    // End of variables declaration//GEN-END:variables
}
